# -*- mode: ruby -*-
# vi: set ft=ruby :

# if ENV['VAGRANT_NODE_DISTR']
#   VAGRANT_NODE_DISTR = ENV['VAGRANT_NODE_DISTR']
# else
#   VAGRANT_NODE_DISTR = "generic/centos9s"
# end

# if ENV['VAGRANT_ZK_VERSION']
#   VAGRANT_ZK_VERSION = ENV['VAGRANT_ZK_VERSION']
# else
#   VAGRANT_ZK_VERSION = "3.6.3"
# end

Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node|
    node.vm.box = "centos/8"
    node.vm.hostname = "node1.example.com"
    node.vm.network "private_network", ip: "192.0.2.101"
    node.vm.provider "qemu" do |qe|
      qe.arch = "x86_64"
      qe.ssh_port = 50122
      qe.machine = "q35"
      qe.cpu = "max"
      qe.smp = 1
      qe.memory = 512
      qe.net_device = "virtio-net-pci"
    end
  end
end


  # config.vm.network :forwarded_port, guest: 22, host: 50122
  # config.vm.define "node1" do |node|
  #   qe.machine = "virt,accel=hvf,highmem=off"

    # node.vbguest.installer_options = { allow_kernel_upgrade: true }
    # node.vm.box = "#{VAGRANT_NODE_DISTR}"
    # node.vm.hostname = "node1.example.com"
    # node.vm.network "private_network", ip: "192.0.2.101"
    # node.vm.provision "shell", path: "./provision.sh", env: {"ZK_VERSION" => "#{VAGRANT_ZK_VERSION}"}
    # node.vm.provider "virtualbox" do |vb|
    #   vb.memory = 1024
    #   vb.cpus = 1
    # end
#   end
# end
