# -*- mode: ruby -*-
# vi: set ft=ruby :

$node_update = <<-'SCRIPT'
  for i in {1..3}; do grep "192.0.2.10$i node$i.example.com node$i" || echo "192.0.2.10$i node$i.example.com node$i" >> /etc/hosts; done
  yum -y install epel-release git bind-utils lsof mc net-tools nmap-ncat tar telnet tree vim wget zip
SCRIPT

Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vbguest.installer_options = { allow_kernel_upgrade: true }
      node.vm.box = "centos/8"
      node.vm.hostname = "node#{i}.example.com"
      node.vm.network "private_network", ip: "192.0.2.10#{i}"
      node.vm.provision "shell", inline: $node_update
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end
end
