# -*- mode: ruby -*-
# vi: set ft=ruby :

## Vagrant Node Variables
if ENV['VAGRANT_NODE_NAME']
    VAGRANT_NODE_NAME = ENV['VAGRANT_NODE_NAME']
  else
    VAGRANT_NODE_NAME = "node1"
    ENV['VAGRANT_NODE_NAME'] = "#{VAGRANT_NODE_NAME}"
end
## Vagrant Node Distributive (RHEL & Debian family are supported by bootstrap.sh)
if ENV['VAGRANT_NODE_DISTR']
    VAGRANT_NODE_DISTR = ENV['VAGRANT_NODE_DISTR']
  else
    VAGRANT_NODE_DISTR = "generic/centos9s"
end
## Number of cores the guest is permitted to use
if ENV['VAGRANT_NODE_SMP']
    VAGRANT_NODE_SMP = ENV['VAGRANT_NODE_SMP']
  else
    VAGRANT_NODE_SMP = 1
end
## Number of memory (in MBytes) the guest is permitted to use
if ENV['VAGRANT_NODE_MEMORY']
    VAGRANT_NODE_SMP = ENV['VAGRANT_NODE_MEMORY']
  else
    VAGRANT_NODE_MEMORY = "512"
end

## Vagrant Node
Vagrant.configure("2") do |config|

  config.vm.define "node" do |node|
    node.vm.box = "#{VAGRANT_NODE_DISTR}"
    node.vm.hostname = "#{VAGRANT_NODE_NAME}.example.com"
    node.vm.provision "node", type: "shell", path: "./bootstrap.sh"

    node.vm.provider :qemu do |qemu|
      qemu.arch = "x86_64"
      qemu.machine = "q35"
      qemu.cpu = "max"
      qemu.smp = "#{VAGRANT_NODE_SMP}"
      qemu.memory = "#{VAGRANT_NODE_MEMORY}"
      qemu.net_device = "virtio-net-pci"
      qemu.extra_netdev_args = "net=192.0.2.0/24,dhcpstart=192.0.2.101"
    end

  end
end
