# -*- mode: ruby -*-
# vi: set ft=ruby :

$node_update = <<-'SCRIPT'
  sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config && systemctl restart sshd
  echo -e '192.0.2.100 control.example.com control' >> /etc/hosts
  for i in {1..3}; do grep "192.0.2.10$i node$i.example.com node$i" || echo "192.0.2.10$i node$i.example.com node$i" >> /etc/hosts; done
  yum -y install epel-release git bind-utils lsof mc net-tools nmap-ncat python3 sshpass tar telnet tree vim wget zip
SCRIPT

$control_user_configure = <<-'SCRIPT'
  ssh-keygen -b 2048 -t rsa -f /home/vagrant/.ssh/id_rsa -q -N ""
  echo -e "Host node*\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null\n  User vagrant\n" > .ssh/config
  chmod 600 .ssh/config
  for i in {1..3}; do sshpass -p 'vagrant' ssh-copy-id -i /home/vagrant/.ssh/id_rsa.pub vagrant@node$i; done
  curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  python3 get-pip.py --user
SCRIPT

Vagrant.configure("2") do |config|

  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vbguest.installer_options = { allow_kernel_upgrade: true }
      node.vm.box = "centos/7"
      node.vm.hostname = "node#{i}.example.com"
      node.vm.network "private_network", ip: "192.0.2.10#{i}"
      node.vm.provision "shell", inline: $node_update
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end

  config.vm.define "control", primary: true do |control|
    control.vbguest.installer_options = { allow_kernel_upgrade: true }
    control.vm.box = "centos/7"
    control.vm.hostname = "control.example.com"
    control.vm.network "private_network", ip: "192.0.2.100"
    control.vm.provision "nodes", type: "shell", inline: $node_update
    control.vm.provision "user", type: "shell", privileged: false, inline: $control_user_configure
    control.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
  end

end
