# -*- mode: ruby -*-
# vi: set ft=ruby :

if ENV['VAGRANT_NODE_COUNT']
  VAGRANT_NODE_COUNT = ENV['VAGRANT_NODE_COUNT']
else
  VAGRANT_NODE_COUNT = 2
end

if ENV['VAGRANT_NODE_DISTR']
  VAGRANT_NODE_DISTR = ENV['VAGRANT_NODE_DISTR']
else
  VAGRANT_NODE_DISTR = "centos/8"
end

Vagrant.configure("2") do |config|

# MANAGED NODES
  (1..VAGRANT_NODE_COUNT.to_i).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vbguest.installer_options = { allow_kernel_upgrade: true }
      node.vm.box = "#{VAGRANT_NODE_DISTR}"
      node.vm.hostname = "node#{i}.example.com"
      node.vm.network "private_network", ip: "192.0.2.10#{i}"
      node.vm.provision "node", type: "shell", path: "./provision-node.sh", env: {"n" => "#{VAGRANT_NODE_COUNT}"}
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end

# CONTROL NODE
  config.vm.define "control", primary: true do |control|
    control.vbguest.installer_options = { allow_kernel_upgrade: true }
    control.vm.box = "#{VAGRANT_NODE_DISTR}"
    control.vm.hostname = "control.example.com"
    control.vm.network "private_network", ip: "192.0.2.100"
    control.vm.provision "node", type: "shell", path: "./provision-node.sh", env: {"n" => "#{VAGRANT_NODE_COUNT}"}
    control.vm.provision "control", type: "shell", path: "./provision-control.sh", privileged: false, env: {"n" => "#{VAGRANT_NODE_COUNT}"}
    control.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
  end

end
