# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

if ENV['VAGRANT_NODE_DISTR']
  VAGRANT_NODE_DISTR = ENV['VAGRANT_NODE_DISTR']
else
  VAGRANT_NODE_DISTR = "generic/centos9s"
end

Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node|
    node.vbguest.installer_options = { allow_kernel_upgrade: true }
    node.vm.box = "#{VAGRANT_NODE_DISTR}"
    node.vm.hostname = "node1.example.com"
    node.vm.network "private_network", ip: "192.0.2.101", virtualbox__intnet: true
    node.vm.provision "node", type: "shell", path: "./provision-node.sh"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end
