# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

if ENV['VAGRANT_NODE_COUNT']
  VAGRANT_NODE_COUNT = ENV['VAGRANT_NODE_COUNT']
else
  VAGRANT_NODE_COUNT = 3
end

if ENV['VAGRANT_NODE_DISTR']
  VAGRANT_NODE_DISTR = ENV['VAGRANT_NODE_DISTR']
else
  VAGRANT_NODE_DISTR = "ubuntu/jammy64"
end

Vagrant.configure("2") do |config|

# LINUX NODES
  (1..VAGRANT_NODE_COUNT.to_i).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vbguest.installer_options = { allow_kernel_upgrade: true }
      node.vm.box = "#{VAGRANT_NODE_DISTR}"
      node.vm.hostname = "node#{i}.example.com"
      node.vm.network "private_network", ip: "192.0.2.10#{i}", virtualbox__intnet: true
      node.vm.provision "node", type: "shell", path: "./provision-node.sh", env: {"n" => "#{VAGRANT_NODE_COUNT}"}
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end
end
